#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=bl
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=1:00:00
#SBATCH --mem=32000M
#SBATCH --output=job_output/baseline_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

conda create -y -n atcs python=3.8.8

source activate atcs

conda install pip



cd advanced-techniques-computational-semantics

pip install -r requirements.txt

conda deactivate
