#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=uni-adam
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=3:00:00
#SBATCH --mem=32000M
#SBATCH --output=job_output/unilstm_adam%A.out



module purge
module load 2021
module load Anaconda3/2021.05

# activate the environment
source activate atcs


python train.py --mode senteval --optimizer adam --verbose --sent_encoder_model unilstm


conda deactivate 
